version: '3.8'
services:
  gateway:
    build: gateway
    container_name: gateway
    ports:
      - "${PORT_GATEWAY}:${PORT_GATEWAY}"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - TZ=GMT

  server:
    build: server
    container_name: server
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/shareit_db
      - TZ=GMT

  database:
    image: postgres:13.7-alpine
    container_name: database
    ports:
      - "6541:${PORT_DATABASE}"
    environment:
      - POSTGRES_DB=shareit_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=GMT